services:
  neo4j:
    image: 'neo4j:latest'
    environment:
      - 'NEO4J_AUTH=neo4j/admin'
    ports:
      - '7687'
      - '7474'
    labels:
      org.springframework.boot.service-connection: neo4j
